---
- name: Install docker
  shell: sleep 30 && curl -fsSL get.docker.com | sh

- name: Install pip
  become: true
  apt:
    name:
      - python3-pip
    update_cache: yes

- name: Install Docker Python SDK
  become: true
  pip:
    name: docker
