dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
# - bash ./tests/run.sh
notifications:
  slack:
    rooms:
      - devops-team-otus:zNQ2Dt4ebbZkU9ifHjiK68bJ#sergei_sergeev
