---
- name: Create Volumes Folders
  become: true
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - /srv/gitlab/config
    - /srv/gitlab/logs
    - /srv/gitlab/data

- name: Change Volumes' owner
  become: true
  file:
    path: /srv/gitlab
    state: directory
    # recurse: yes
    owner: ubuntu
    group: ubuntu

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /srv/gitlab/docker-compose.yml

- name: Upgrade pip
  become: true
  pip:
    name:
      - pip
    extra_args: --upgrade

- name: Install docker-compose sdk
  become: true
  pip:
    name:
      - docker-compose

- name: Run docker-compose
  become: true
  docker_compose:
    project_src: /srv/gitlab
    state: present
